#
# Makefile for ArgonLV implementation of Motorola GPIO API.
#
obj-y				:= iomux_init.o gpio_init.o base.o

obj-${CONFIG_MOT_FEAT_GPIO_API_BTPOWER} 	+= btpower.o
obj-${CONFIG_MOT_FEAT_GPIO_API_CSI}		+= csi.o
obj-${CONFIG_MOT_FEAT_GPIO_API_DAI}		+= dai.o
obj-${CONFIG_MOT_FEAT_GPIO_API_ETHERNET}	+= ethernet.o
obj-${CONFIG_MOT_FEAT_GPIO_API_ETM}		+= etm.o
obj-${CONFIG_MOT_FEAT_GPIO_API_LCD}		+= lcd.o
obj-${CONFIG_MOT_FEAT_GPIO_API_LIGHTING}	+= lighting.o
obj-${CONFIG_MOT_FEAT_GPIO_API_MC13783}		+= mc13783.o
obj-${CONFIG_MOT_FEAT_GPIO_API_SDHC}		+= sdhc.o
obj-${CONFIG_MOT_FEAT_GPIO_API_USBHS}		+= usb_hs.o
obj-${CONFIG_MOT_FEAT_GPIO_API_WLAN}		+= wlan.o
